#define SBLBadWhenErrorMessage @"called when() without specifying a method call on a mock"
#define SBLBadVerifyErrorMessage @"called verify() without specifying a method call on a mock"
#define SBLBadUsage @"SBLBadUsage"
#define SBLMethodWasCalledUnexpectedly @"Mock was called when no interactions expected"
#define SBLBadTimesProvided @"Number of times must be 0 or more"
#define SBLBadAtLeastTimesProvided @"Number of atLeast times must be 1 or more"
#define SBLBadMatchersProvided @"If one non-object parameter is given a matcher, all non-object parameters must be given matchers"
#define SBLBadMatcherRegistration @"Matchers should not be used outside of when() or verify() calls"
#define SBLAtLeastCannotBeGreaterThanAtMost @"atLeast must be less than or equal to atMost in between(atLeast, atMost)"